"""add plain_password to business

Revision ID: 046f796a6d10
Revises: 58fb378ec73b
Create Date: 2026-06-16 07:50:59.950470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046f796a6d10'
down_revision: Union[str, Sequence[str], None] = '58fb378ec73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('plain_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'plain_password')
    # ### end Alembic commands ###
