"""add review_message_id

Revision ID: 28fa1e820007
Revises: 88a94455f574
Create Date: 2026-06-18 10:33:03.144693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fa1e820007'
down_revision: Union[str, Sequence[str], None] = '88a94455f574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('review_message_id', sa.Integer(), nullable=True))
    op.alter_column('reviews', 'reply_comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'reply_comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('bookings', 'review_message_id')
    # ### end Alembic commands ###
