"""add_telegram_id_to_master

Revision ID: 58fb378ec73b
Revises: 845124c47402
Create Date: 2026-06-16 07:21:30.030329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58fb378ec73b'
down_revision: Union[str, Sequence[str], None] = '845124c47402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('telegram_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_masters_telegram_id'), 'masters', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_masters_telegram_id'), table_name='masters')
    op.drop_column('masters', 'telegram_id')
    # ### end Alembic commands ###
