"""add_description_to_masters

Revision ID: 674c61eda3b6
Revises: 9b53be643cd1
Create Date: 2026-06-15 15:11:01.498837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674c61eda3b6'
down_revision: Union[str, Sequence[str], None] = '9b53be643cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'description')
    # ### end Alembic commands ###
