"""Add image to services

Revision ID: 8e22e7c2c7cd
Revises: ef4e00f271eb
Create Date: 2026-06-15 05:35:47.531816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e22e7c2c7cd'
down_revision: Union[str, Sequence[str], None] = 'ef4e00f271eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'image')
    # ### end Alembic commands ###
