"""add_created_at_and_owner_telegram_to_business

Revision ID: 94b80a646f2c
Revises: f0c72611e267
Create Date: 2026-06-16 08:34:46.700186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b80a646f2c'
down_revision: Union[str, Sequence[str], None] = 'f0c72611e267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('owner_telegram', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'created_at')
    op.drop_column('businesses', 'owner_telegram')
    # ### end Alembic commands ###
