"""add_branding_and_settings

Revision ID: 9b53be643cd1
Revises: 8e22e7c2c7cd
Create Date: 2026-06-15 14:37:38.649797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b53be643cd1'
down_revision: Union[str, Sequence[str], None] = '8e22e7c2c7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('instagram', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('telegram', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('cover_image', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('primary_color', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('min_buffer_hours', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('max_booking_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'max_booking_days')
    op.drop_column('businesses', 'min_buffer_hours')
    op.drop_column('businesses', 'timezone')
    op.drop_column('businesses', 'currency')
    op.drop_column('businesses', 'primary_color')
    op.drop_column('businesses', 'cover_image')
    op.drop_column('businesses', 'telegram')
    op.drop_column('businesses', 'instagram')
    op.drop_column('businesses', 'description')
    # ### end Alembic commands ###
