"""add bot fields to business

Revision ID: f0c72611e267
Revises: 046f796a6d10
Create Date: 2026-06-16 08:15:33.544335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c72611e267'
down_revision: Union[str, Sequence[str], None] = '046f796a6d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('client_bot_username', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('client_bot_token', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('master_bot_username', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('master_bot_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'master_bot_token')
    op.drop_column('businesses', 'master_bot_username')
    op.drop_column('businesses', 'client_bot_token')
    op.drop_column('businesses', 'client_bot_username')
    # ### end Alembic commands ###
